services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    restart: unless-stopped

  client:
    build:
      context: ./client/Calculator
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - "8100:80"
    restart: unless-stopped
