apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent-service
  namespace: devops-tools
spec:
  selector:
    app: jenkins-server
  ports:
    - name: jnlp
      port: 50000
      targetPort: 50000
  type: ClusterIP   
