apiVersion: v1
kind: Service
metadata:
  name: jenkins-frontend
  namespace: devops-tools
  labels:
    app: jenkins-frontend
spec:
  selector:
    app: jenkins-frontend
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30100