apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: zlhu3/sample-server
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
